In [1]:
import numpy as np; import pandas as pd

In [2]:
a = np.arange(10)
b = a[2:7]
b[0] = 99
print(a)
# 1.a. Apa hasil dari a? (poin 5)
# 1.b. Jelaskan mengapa nilai a ikut berubah ketika b diubah! (poin 10)
# 1.c. Bagaimana cara agar perubahan pada b tidak mempengaruhi a? (poin 5)

[ 0  1 99  3  4  5  6  7  8  9]


In [3]:
x = np.array([[1, 2, 3],
              [4, 5, 6]])
y = np.array([[10],
              [20],
              [30]])
z = x * y
print(z)
# 2.a. apa hasil dari z? (poin 5)
# 2.b. Jelaskan secara visual matematis, bagaimana mekanisme kerja dari operasi tersebut (operasi z)! (poin 10)

ValueError: operands could not be broadcast together with shapes (2,3) (3,1) 

In [4]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
c = np.concatenate((a, b), axis=0)
d = np.concatenate((a, b), axis=1)
print(c)
print(d)
# 3.a. Apa hasil dari c dan d? (poin 5)
# 3.b. Jelaskan perbedaan penggunaan axis=0 dan axis=1! (poin 5)
# 3.c. Bagaimana mekanisme kerja dari operasi tersebut (operasi c dan d)! (poin 10)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


In [5]:
a = np.array([[10, 20, 30, 40, 50, 60],
              [70, 80, 90, 100, 110, 120]])
x = np.split(a, 2, axis=0)
y = np.split(a, 3, axis=1)
print(x)
print(y)
# 4.a. Apa hasil dari x dan y? (poin 5)
# 4.b. Bagaimana mekanisme kerja dari operasi tersebut (operasi x dan y)! (poin 10)

[array([[10, 20, 30, 40, 50, 60]]), array([[ 70,  80,  90, 100, 110, 120]])]
[array([[10, 20],
       [70, 80]]), array([[ 30,  40],
       [ 90, 100]]), array([[ 50,  60],
       [110, 120]])]


In [6]:
df = pd.DataFrame({
    "usia": [21, 19, 22, 18, 23],
    "nilai": [80, 60, 90, 75, 85]})
b = df.loc[(df["usia"] > 20) & (df["nilai"] > 80)]
print(b)
# 5.a. Apa hasil dari b? (poin 5)
# 5.b. Jelaskan perbedaan penggunaan iloc dan loc! (poin 10)
# 5.c. Buatlah satu baris kode untuk menampilkan kolom rata-rata nilai! (poin 15)

   usia  nilai
2    22     90
4    23     85
